spring:
  application:
    name: taskmanager
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/taskmanager?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:rootpassword}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET:task-manager-jwt-secret-key-minimum-32-characters-long}
  expirationMs: 3600000
  refreshExpirationMs: 604800000
logging:
  level:
    com.example.taskmanager: DEBUG