spring:
  application:
    name: taskmanager
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/taskmanager?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:rootpassword}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
server:
  port: 8080
  servlet:
    context-path: /
management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    com.example.taskmanager: INFO